# Conda environment configuration for AI Skill Planner
name: ai_skill_planner
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=23.3.1

  # API Framework
  - fastapi=0.104.1
  - uvicorn=0.24.0

  # Data Models and Validation
  - pydantic=2.5.0

  # Math and Scientific Computing
  - numpy=1.24.3
  - scipy=1.11.3

  # Testing
  - pytest=7.4.3
  - pytest-asyncio=0.21.1
  - httpx=0.25.0

  # Development Tools
  - black=23.10.1
  - flake8=6.1.0

  # Additional dependencies via pip
  - pip:
    - python-multipart  # For form data handling in FastAPI
    - PyJWT==2.8.0      # JWT token handling
    - passlib[bcrypt]==1.7.4  # Password hashing
    - python-jose[cryptography]==3.3.0  # Additional crypto support
    - cryptography>=41.0.0  # Encryption library
    - websockets>=11.0.0  # WebSocket support